/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xianrui_stackblur_NativeBlurProcess */

#ifndef _Included_com_xianrui_stackblur_NativeBlurProcess
#define _Included_com_xianrui_stackblur_NativeBlurProcess
#ifdef __cplusplus
extern "C" {
#endif



JNIEXPORT void JNICALL Java_com_xianrui_stackblur_NativeBlurProcess_functionToBlur
        (JNIEnv *env, jclass clzz,
                                                                     jintArray pixels,jint width,jint height, jint radius,
                                                                     jint threadCount, jint threadIndex,
                                                                     jint round);



#ifdef __cplusplus
}
#endif
#endif

